<?php
namespace restphp\validate;

/**
 * Class RestValidateConstant
 * @package restphp\validate
 */
class RestValidateConstant {
    const ARGUMENT_LENGTH_ERROR = 'ARGUMENT_LENGTH_ERROR';
    const ARGUMENT_NOTNULL = 'ARGUMENT_NOTNULL';
    const ARGUMENT_NOT_MOBILE = 'ARGUMENT_NOT_MOBILE';
    const ARGUMENT_NOT_EMAIL = 'ARGUMENT_NOT_EMAIL';
    const ARGUMENT_RANGE_ERROR = 'ARGUMENT_RANGE_ERROR';
    const ARGUMENT_NOT_DOMAIN = 'ARGUMENT_NOT_DOMAIN';
    const ARGUMENT_INT_ERROR = 'ARGUMENT_INT_ERROR';
    const ARGUMENT_NOT_IPV4 = 'ARGUMENT_NOT_IPV4';
    const ARGUMENT_CUSTOMER_ERROR = 'ARGUMENT_CUSTOMER_ERROR';
    const ARGUMENT_CUSTOMER_METHOD_ERROR = 'ARGUMENT_CUSTOMER_METHOD_ERROR';
    const ARGUMENT_DATE_FORMAT_ERROR = 'ARGUMENT_DATE_FORMAT_ERROR';
}